In [1]:
import numpy as np
from sympy import *

Пример 1

In [2]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [3]:
arr = np.matrix([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [4]:
arr = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a = Matrix([[1,2],[3,4]])
a

Matrix([
[1, 2],
[3, 4]])

Вычисление определителя

In [6]:
arr = np.matrix('1 2; 3 4')
detA = arr[0,0] * arr[1,1] - arr[0,1] * arr[1, 0]
detA

-2

In [7]:
detA = np.linalg.det(arr)
print(detA)

-2.0000000000000004


In [8]:
det(a)

-2

Упражнение 2.1

In [9]:
v=Matrix([[-1,4],[-5,2]])
det(v)

18

In [10]:
a,b=symbols('a b')
v=Matrix([[a+b, a-b],[a+b,a-b]])
det(v)

0

In [11]:
x = symbols('x')
v = Matrix([[x, (x+1)],[-4, (x+1)]])
det(v)

x**2 + 5*x + 4

Упражнение 2.2

In [12]:
v = Matrix([[1,2,3],[4,5,6],[7,8,1]])
det(v)

24

In [13]:
v = Matrix([[3,4,-5],[8,7,-2],[2,-1,8]])
det(v)

0

In [14]:
a,b,c,x = symbols('a b c x')
v = Matrix([[a+x,x,x],[x,b+x,x],[x,x,c+x]])
det(v)

a*b*c + a*b*x + a*c*x + b*c*x

In [15]:
a,b,c = symbols('a b c')
v = Matrix([[sin(a),cos(a),1],[sin(b),cos(b),1],[sin(c),cos(c),1]])
det(v)

sin(a)*cos(b) - sin(a)*cos(c) - sin(b)*cos(a) + sin(b)*cos(c) + sin(c)*cos(a) - sin(c)*cos(b)

In [16]:
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
print(A)
B = np.matrix('-4; 10; 8')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
z = np.linalg.det(Z_m) / A_det
print(x)
print(y)
print(z)

[[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
[[-4]
 [10]
 [ 8]]
13.999999999999996
[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[ 3 -4  2]
 [ 1 10 -1]
 [ 2  8  1]]
[[ 3 -1 -4]
 [ 1  4 10]
 [ 2  3  8]]
-1.0000000000000009
3.0000000000000013
1.0


Упражнение 2.3

In [17]:
A = np.matrix('3 -5; 2 7')
print(A)
B = np.matrix('13; 81')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
print(x)
print(y)

[[ 3 -5]
 [ 2  7]]
[[13]
 [81]]
31.0
[[13 -5]
 [81  7]]
[[ 3 13]
 [ 2 81]]
16.000000000000007
7.000000000000001


In [18]:
A = np.matrix('3 -4; -6 8')
print(A)
B = np.matrix('-6; 12')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
print(x)
print(y)

[[ 3 -4]
 [-6  8]]
[[-6]
 [12]]
0.0
[[-6 -4]
 [12  8]]
[[ 3 -6]
 [-6 12]]
nan
nan


C:\Users\user\AppData\Local\Temp\ipykernel_30964\930468612.py:13: RuntimeWarning: invalid value encountered in double_scalars
  x = np.linalg.det(X_m) / A_det
C:\Users\user\AppData\Local\Temp\ipykernel_30964\930468612.py:14: RuntimeWarning: invalid value encountered in double_scalars
  y = np.linalg.det(Y_m) / A_det


Определитель равен 0

In [19]:
A = np.matrix('7 2 3; 5 -3 2; 10 -11 5')
print(A)
B = np.matrix('15; 15; 36')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
z = np.linalg.det(Z_m) / A_det
print(x)
print(y)
print(z)

[[  7   2   3]
 [  5  -3   2]
 [ 10 -11   5]]
[[15]
 [15]
 [36]]
-36.0
[[ 15   2   3]
 [ 15  -3   2]
 [ 36 -11   5]]
[[ 7 15  3]
 [ 5 15  2]
 [10 36  5]]
[[  7   2  15]
 [  5  -3  15]
 [ 10 -11  36]]
1.999999999999998
-1.0
0.999999999999999


In [20]:
A = np.matrix('2 1 0; 1 0 3; 0 5 -1')
print(A)
B = np.matrix('5; 16; 10')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x = np.linalg.det(X_m) / A_det
y = np.linalg.det(Y_m) / A_det
z = np.linalg.det(Z_m) / A_det
print(x)
print(y)
print(z)

[[ 2  1  0]
 [ 1  0  3]
 [ 0  5 -1]]
[[ 5]
 [16]
 [10]]
-28.99999999999999
[[ 5  1  0]
 [16  0  3]
 [10  5 -1]]
[[ 2  5  0]
 [ 1 16  3]
 [ 0 10 -1]]
[[ 2  1  5]
 [ 1  0 16]
 [ 0  5 10]]
1.0
3.000000000000001
5.000000000000001


Упражнение 2.4

In [21]:
A = Matrix([[3, -5],[2, 7]])
print(A)
B = Matrix([[13],[81]])
print(B)
A_det = det(A)
print(A_det)
X_m = Matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = Matrix(A)
Y_m[:, 1] = B
print(Y_m)
x = det(X_m) / A_det
y = det(Y_m) / A_det
print(x)
print(y)

# Проверка через методом *
X = Matrix([[x], [y]])
X = Matrix(A*X)
print(X-B)

Matrix([[3, -5], [2, 7]])
Matrix([[13], [81]])
31
Matrix([[13, -5], [81, 7]])
Matrix([[3, 13], [2, 81]])
16
7
Matrix([[0], [0]])


In [22]:
A = Matrix([[7,2,3],[5,-3,2],[10,-11,5]])
print(A)
B = Matrix([[15],[15],[36]])
print(B)
A_det = det(A)
print(A_det)
X_m = Matrix(A)
X_m[:, 0] = B
print(X_m)
Y_m = Matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = Matrix(A)
Z_m[:, 2] = B
print(Z_m)
x = det(X_m) / A_det
y = det(Y_m) / A_det
z = det(Z_m) / A_det
print(x)
print(y)
print(z)

# Проверка через методом *
X = Matrix([[x], [y], [z]])
X = Matrix(A*X)
print(X-B)

Matrix([[7, 2, 3], [5, -3, 2], [10, -11, 5]])
Matrix([[15], [15], [36]])
-36
Matrix([[15, 2, 3], [15, -3, 2], [36, -11, 5]])
Matrix([[7, 15, 3], [5, 15, 2], [10, 36, 5]])
Matrix([[7, 2, 15], [5, -3, 15], [10, -11, 36]])
2
-1
1
Matrix([[0], [0], [0]])


Упражнение 2.5

In [23]:
A = np.matrix('3 -5; 2 7')
print(A)
B = np.matrix('13; 81')
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X


[[ 3 -5]
 [ 2  7]]
[[13]
 [81]]
[[ 0.22580645  0.16129032]
 [-0.06451613  0.09677419]]


matrix([[16.],
        [ 7.]])

In [24]:
A = np.matrix('3 -4; -6 8')
print(A)
B = np.matrix('-6; 12')
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[ 3 -4]
 [-6  8]]
[[-6]
 [12]]


LinAlgError: Singular matrix

Нет решения

In [25]:
A = np.matrix('7 2 3; 5 -3 2; 10 -11 5')
print(A)
B = np.matrix('15; 15; 36')
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[  7   2   3]
 [  5  -3   2]
 [ 10 -11   5]]
[[15]
 [15]
 [36]]
[[-0.19444444  1.19444444 -0.36111111]
 [ 0.13888889 -0.13888889 -0.02777778]
 [ 0.69444444 -2.69444444  0.86111111]]


matrix([[ 2.],
        [-1.],
        [ 1.]])

In [26]:
A = np.matrix('2 1 0; 1 0 3; 0 5 -1')
print(A)
B = np.matrix('5; 16; 10')
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[ 2  1  0]
 [ 1  0  3]
 [ 0  5 -1]]
[[ 5]
 [16]
 [10]]
[[ 0.51724138 -0.03448276 -0.10344828]
 [-0.03448276  0.06896552  0.20689655]
 [-0.17241379  0.34482759  0.03448276]]


matrix([[1.],
        [3.],
        [5.]])